### ISSUE TITLE
Is it that time again? Re-pull and update the got_chars object from the GoT database

### ISSUE THREAD

**Issue by stufield** [jennybc/repurrrsive#13]
A light lifting ... time for an update from the database to see if any new characters and entries have been populated in the past year or two.

Also, working check to ensure that the underlying machinery for the update is still in working order.

Wish me luck!

**Comment by stufield** [comment]
Hello @jennybc, poking around a little bit, it seems the `gh` and `got` data wranglers (in `data-raw`) depend on an experimental function `as_xml()`, that lives in a specific branch of the `xml2` package. This dev version of the `xml2` package is less than `v1.1.1`, on which the `tidyverse` depends. So the call `library(tidyverse)` fails if you run the two wrangler scripts with the appropriate `xml2` dev package installed. I see a couple possible options:

1. update your dev branch version to be `v1.1.1` or greater
1. specifically load only the minimal required packages in the script with specific `library()` calls, e.g. `library(purrr); library(dplyr)` etc.

There are probably more options, but those seem most obvious. I can update and submit a PR if you would prefer option 2.

**Comment by jennybc** [comment]
I did a pilot study and re-ran the scripts to download and wrangle GoT data.

I see a few very tiny changes in data downloaded but not in, say, the JSON we expose as `got_chars.json`. So I'm not sure this is going to change any exported / exposed objects. Was there some specific change you were hoping to pick up? I recall there was.

That being said, I'm happy for this to get an update.

There should be a way to use `xml2::as_xml_document()` instead of my experimental `as_xml()` function. But I can't immediately get it to work. Your tolerance for fiddling with this depends on whether you have other reasons to get more facile with XML and xml2. I think it is possible something about `as_xml_document()` is a bit buggy, which would be nice to know.

**Comment by stufield** [comment]
Yes, that was my recollection also, that the JSON files didn't change (at lease Git says they didn't), but the *.rda files did (which has always confused me a little, I've seen it before, the source didn't change but the *.rda resulting from it differs from what Git thinks).

I'd be happy to tinker around a bit with `xml2::as_xml_document()` to see if I can avoid the experimental function (and thus the scripts will run cleaner). However, my XML is horrible, so not sure how successful I'll be. My XML is worse than my SQL if that's possible.

The update that triggered my OCD was that Daenerys Targaryen's parents were empty, and as everyone knows her parents were Aerys II (the Mad Kind) and Rhaella Targaryen. :)

I did notice that the docs say that the `got_chars` object is of length 29, where in fact it's 30. Just a docs update issue. Perhaps I can just do that as a separate PR as is totally unrelated. If you'd like.

**Comment by stufield** [comment]
I don't think much has changed. Though interestingly there's an odd change in the website location but only in some entries. I'm not sure this mean anything is broken, looks like someone updated the code to ensure the web locations were unified and didn't rerun all the JSON files. But, John Snow seems to have gone the wrong way (removed the 'www') and the House of Tully seems to be corrected. Again, doubt this is a substantive change.

John Snow:
<img width="1001" alt="screen shot 2019-01-24 at 2 02 59 pm" src="https://user-images.githubusercontent.com/25203086/51708304-d3ea6500-1fe0-11e9-9f49-e44f62ee69e8.png">

House Tully:
<img width="996" alt="screen shot 2019-01-24 at 2 26 04 pm" src="https://user-images.githubusercontent.com/25203086/51709646-32fda900-1fe4-11e9-925d-6b913cb769a1.png">

**Comment by jennybc** [comment]
My instinct is to leave this alone since we don't think the data would actually change.

I think you need to take up your campaign re: Daenerys's pedigree with the data source 😁 which I *think* is this:

https://github.com/joakimskoog/AnApiOfIceAndFire

Re-creating the XML w/o my experimental branch of xml2 would be nice but it's not urgent.

> I did notice that the docs say that the got_chars object is of length 29, where in fact it's 30. Just a docs update issue. Perhaps I can just do that as a separate PR as is totally unrelated. If you'd like.

Sounds good!

**Comment by stufield** [comment]
Ok, PR on the way!
